---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: '在为Site Recovery Manager \(SRM\)运行Storage Replication Adapter \(SRA\)之前、应先设置存储系统。' 
---
= 为SAN和NAS环境配置SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在运行适用于Site Recovery Manager (SRM)的Storage Replication Adapter (SRA)之前、应先设置存储系统。



== 为SAN环境配置SRA

* 您需要的内容 *

您应在受保护站点和恢复站点上安装以下程序：

* SRM
+
有关安装 SRM 的文档位于 VMware 站点上。

+
https://docs.vmware.com/en/Site-Recovery-Manager/index.html["VMware Site Recovery Manager 文档"]

* SRA
+
此适配器已安装在SRM上。



* 步骤 *

. 验证主 ESXi 主机是否已连接到受保护站点上主存储系统中的 LUN 。
. 确认LUN位于 `ostype`主存储系统上已将选项设置为_vmware_的igrou中。
. 验证恢复站点上的ESXi主机是否与Storage Virtual Machine (SVM)建立了适当的iSCSI连接。二级站点ESXi主机应有权访问二级站点存储、而主站点ESXi主机应有权访问主站点存储。
+
为此、您可以验证ESXi主机是否已在SVM上连接本地LUN、也可以 `iscsi show initiators`在SVM上使用命令。在ESXi主机中检查映射的LUN的LUN访问、以验证iSCSI连接。





== 为NAS环境配置SRA

* 您需要的内容 *

您应在受保护站点和恢复站点上安装以下程序：

* SRM
+
有关安装 SRM 的文档，请参见 VMware 站点。

+
https://docs.vmware.com/en/Site-Recovery-Manager/index.html["VMware Site Recovery Manager 文档"]

* SRA
+
适配器安装在 SRM 和 SRA 服务器上。



* 步骤 *

. 验证受保护站点上的数据存储库是否包含已向 vCenter Server 注册的虚拟机。
. 验证受保护站点上的 ESXi 主机是否已挂载 Storage Virtual Machine （ SVM ）中的 NFS 导出卷。
. 使用阵列管理器向导向 SRM 添加阵列时，验证是否在 * NFS 地址 * 字段中指定了有效地址，例如存在 NFS 导出的 IP 地址，主机名或 FQDN 。
.  `ping`在恢复站点的每个ESXi主机上使用命令验证此主机是否具有一个VMkernel端口、此端口可访问用于从SVM提供NFS导出的IP地址。

